# Generated by Django 5.2 on 2025-05-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['start_time']},
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence',
            field=models.CharField(choices=[('NONE', 'None'), ('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], default='NONE', help_text='Recurrence pattern for the booking', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_end',
            field=models.DateTimeField(blank=True, help_text='End date for recurring bookings', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='recurrence_id',
            field=models.CharField(blank=True, help_text='Unique identifier for a series of recurring bookings', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['recurrence_id'], name='bookings_bo_recurre_7aa39c_idx'),
        ),
    ]
